server:
  port: 8080

spring:
  application:
    name: ruxpress-back
  profiles:
    active: local
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 60MB
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  messages:
    basename: messages/messages
    encoding: UTF-8

app:
  jwt:
    secret: ${JWT_SECRET:defaultLocalSecretKeyForDevelopmentOnlyDoNotUseInProduction1234567890}
    expiration: ${JWT_EXPIRATION:86400000}
