storage:
  type: s3
  s3:
    bucket: ${S3_BUCKET}
    region: ${S3_REGION:ap-northeast-2}
    access-key: ${S3_ACCESS_KEY}
    secret-key: ${S3_SECRET_KEY}

spring:
  mail:
      host: ${MAIL_HOST:}
      port: ${MAIL_PORT:}
      username: ${MAIL_USERNAME:}
      password: ${MAIL_PASSWORD:}
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
  datasource:
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT:3306}/${DB_NAME}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: none

logging:
  level:
    root: WARN
    com.ruxpress: INFO
