spring:
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:mariadb://mariadb:3306/${DB_NAME:ruxpress}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DB_USERNAME:ruxpress}
    password: ${DB_PASSWORD:ruxpress}
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: validate

logging:
  level:
    com.ruxpress: INFO
