spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ljyeon131@gmail.com
    password: tknq coai rzha cudx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:mariadb://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:ruxpress}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DB_USERNAME:ruxpress}
    password: ${DB_PASSWORD:ruxpress}
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: validate

logging:
  level:
    com.ruxpress: INFO
