push:
  dev-api-enabled: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/ruxpress_push
    username: push
    password: push
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

logging:
  level:
    com.ruxpress.push: DEBUG
    org.apache.kafka: INFO
