name: Deploy Prod

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH to prod
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST_PROD }}
          username: ${{ secrets.SSH_USER_PROD }}
          key: ${{ secrets.SSH_PRIVATE_KEY_PROD }}
          script: |
            set -e
            cd /svc/RuxPress
            git remote set-url origin https://${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git
            git pull origin master
            ./script/rebuild.sh
